services:
#    aavv_strapp_api.example:
#        class: AAVVStrapp\ApiBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    core_validator:
        class: AAVVStrapp\ApiBundle\Services\CoreValidator
