# Listado de localidad
aavv_strapp_api_location_list:
  path: /list
  defaults: { _controller: AAVVStrappApiBundle:Location:list }
  methods:  [GET]

# Registro de localidad
aavv_strapp_api_location_register:
  path: /register
  defaults: { _controller: AAVVStrappApiBundle:Location:register }
  methods:  [POST]

# Edición de localidad
aavv_strapp_api_location_edit:
  path: /edit
  defaults: { _controller: AAVVStrappApiBundle:Location:edit }
  methods:  [POST]

# Eliminar localidad
aavv_strapp_api_location_delete:
  path: /delete
  defaults: { _controller: AAVVStrappApiBundle:Location:delete }
  methods:  [POST]

# Obtener datos de la localidad
aavv_strapp_api_location_read:
  path: /read
  defaults: { _controller: AAVVStrappApiBundle:Location:read }
  methods:  [GET]