# Listado de viajes
aavv_strapp_api_travel_list:
  path: /list
  defaults: { _controller: AAVVStrappApiBundle:Travel:list}
  methods:  [GET]

# Registro de viaje
aavv_strapp_api_travel_register:
  path: /register
  defaults: { _controller: AAVVStrappApiBundle:Travel:register }
  methods:  [POST]

# Edición de viaje
aavv_strapp_api_travel_edit:
  path: /edit
  defaults: { _controller: AAVVStrappApiBundle:Travel:edit }
  methods:  [POST]

# Eliminar viaje
aavv_strapp_api_travel_delete:
  path: /delete
  defaults: { _controller: AAVVStrappApiBundle:Travel:delete }
  methods:  [POST]

# Obtener datos de la localidad
aavv_strapp_api_travel_read:
  path: /read
  defaults: { _controller: AAVVStrappApiBundle:Travel:read }
  methods:  [GET]