AAVVStrapp\ApiBundle\Entity\Location:
    type: entity
    table: location
    repositoryClass: AAVVStrapp\ApiBundle\Repository\LocationRepository

    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
      # C贸digo del viaje
      location_code:
        type: string
      # Nombre de la localidad
      name:
        type: string
      # Informaci贸n adicional
      additional_information:
        type: string
      # Ultima actualizaci贸n
      last_update:
        type: datetime
      # Fecha de creaci贸n
      created:
        type: datetime

    oneToMany:
        # Viajes de origen
        origins_travel:
            targetEntity: AAVVStrapp\ApiBundle\Entity\Travel
            mappedBy: origin_location
            cascade: ["persist"]
        # Viajes de destino
        destinies_travel:
            targetEntity: AAVVStrapp\ApiBundle\Entity\Travel
            mappedBy: destitny_location
            cascade: ["persist"]

    # Eventos que se ejecutan al editar un elemento
    lifecycleCallbacks:
        prePersist: [ updateCreated, updateLastUpdate ]
        postPersist: [ updateLastUpdate ]